from os import environ
from pathlib import Path

CWD = Path.cwd()
DEFAULT_FILTERS = CWD / "filters.json"

DEFAULT_DATA_DIRECTORY = CWD / "data"
DEFAULT_RAW_DIRECTORY = DEFAULT_DATA_DIRECTORY / "raw"
DEFAULT_CLEANSED_DIRECTORY = DEFAULT_DATA_DIRECTORY / "cleansed"
DEFAULT_PARSED_DIRECTORY = DEFAULT_DATA_DIRECTORY / "parsed"

USER_DIRECTORY = Path(environ["HOME"])
DOCUMENTS_DIRECTORY = USER_DIRECTORY / "Documents"
